# Generated by Django 4.0.5 on 2023-01-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('sunlight', models.CharField(choices=[('Full', 'Full'), ('Semi', 'Semi'), ('Dark', 'Dark')], max_length=30)),
                ('water_how_often', models.IntegerField()),
                ('last_watering', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantcare.room')),
            ],
        ),
    ]
